services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: public.ecr.aws/v4q1e7f2/server-django-ec2:server
    command: gunicorn contentscour.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/server/staticfiles
      - media_volume:/home/app/server/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    container_name: nginx
    build: ./nginx
    image: public.ecr.aws/v4q1e7f2/server-django-ec2:nginx
    restart: always
    volumes:
      - static_volume:/home/app/server/staticfiles
      - media_volume:/home/app/server/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
      - server
  acme-companion:
    image: nginxproxy/acme-companion
    env_file:
      - ./.env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: