services:
  server:
    build: .
    command: ["sh", "-c", "python3 -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - ./.env
  frontend:
    build:
      context: ./front
    image: front
    hostname: front
    command: npm run dev -- --host
    ports:
      - 3000:3000
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - /front/node_modules
      - ./front:/front
  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    image: nginx
    ports:
      - 80:7999
    volumes:
      - ./nginx/default_local:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

volumes:
  postgres_data: