services:
  server:
    build: .
    command: ["sh", "-c", "python3 -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - ./.env
  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data: