services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn contentscour.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/server/staticfiles
      - media_volume:/home/app/server/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/server/staticfiles
      - media_volume:/home/app/server/mediafiles
    ports:
      - 1337:80
    depends_on:
      - server

volumes:
  postgres_data:
  static_volume:
  media_volume: